// void main(
    // // Input attributes
    // float4 in v0 : POSITION,  // Corresponds to "ATTRIBUTE_v0(mediump vec4)"
    // float2 in v9 : TEXCOORD0, // Corresponds to "ATTRIBUTE_v9(mediump vec2)"

    // // Output "varyings"
    // float4 out oPos : POSITION, // Equivalent to "gl_Position"
    // float2 out oT0  : TEXCOORD0  // Equivalent to "VARYING_oT0(mediump vec2)"
// )
// {
    // // Pass the vertex position directly to the output
    // oPos = v0 * 0.000007;

    // // Pass the texture coordinate directly to the output
    // oT0 = v9; 
// }

// PROGRAM 2
// Cg Vertex Shader 

void main(
    // Inputs (attributes)
    in float4 v0 : POSITION,   // corresponds to "ATTRIBUTE_v0(mediump vec4)"
    in float2 v9 : TEXCOORD0,  // corresponds to "ATTRIBUTE_v9(mediump vec2)"

    // Outputs (varyings)
    out float4 oPos : POSITION, // equivalent to gl_Position
    out float2 oT0  : TEXCOORD0 // equivalent to "VARYING_oT0(mediump vec2)"
)
{
    // Pass position
    oPos = v0;

    // Pass UV coordinates
    oT0 = v9;
}
