// profile sce_fp_psp2
// Cg Fragment Shader
// Used fullscreen since the start

// Uniform texture sampler (low precision)
// sampler2D u0;

// Uniform gamma correction factors (low precision)
//float3 D3D_GAMMA_FACTORS;

// Varying texture coordinate (from TEXCOORD0)
void main(
    float2 oT0 : TEXCOORD0,
    float4 out outColor : COLOR,
    uniform sampler2D u0 : TEXUNIT0,
    uniform float3 D3D_GAMMA_FACTORS
)
{
    // Sample the texture at the given coordinates
    oT0.y = 1.0 - oT0.y;
    float4 pix = tex2D(u0, oT0);
    
    // Apply gamma correction to the RGB channels
    float4 color;
    color.a = pix.a;
    color.rgb = pow(pix.rgb, D3D_GAMMA_FACTORS);
    outColor = color; 
    //outColor = float4(oT0.x,0,0,0) + pix; 
}
