cd /vita-dev/vitaGL
#make clean
make HAVE_WRAPPED_ALLOCATORS=1 HAVE_PROFILING=0 SOFTFP_ABI=1 LOG_ERRORS=0 HAVE_GLSL_SUPPORT=1 USE_SCRATCH_MEMORY=1 CIRCULAR_VERTEX_POOL=1 HAVE_SHARK_LOG=0 NO_DEBUG=1 HAVE_DEBUGGER=1 SAFE_UNIFORMS=1 STORE_DEPTH_STENCIL=1 HAVE_TEXTURE_CACHE=0 INDICES_SPEEDHACK=0 DRAW_SPEEDHACK=2 install 
cd /vita-dev/soulcalibur_vita/build
cmake ..
make clean
make send
#make