cd /vita-dev/vitaGL
make clean
make -j64 HAVE_UNFLIPPED_FBOS=0 UNPURE_TEXTURES=1 HAVE_WRAPPED_ALLOCATORS=1 HAVE_PROFILING=0 SOFTFP_ABI=1 LOG_ERRORS=0 HAVE_GLSL_SUPPORT=1 USE_SCRATCH_MEMORY=1 CIRCULAR_VERTEX_POOL=2 HAVE_SHARK_LOG=0 NO_DEBUG=1 HAVE_DEBUGGER=0 SAFE_UNIFORMS=1 STORE_DEPTH_STENCIL=0 HAVE_TEXTURE_CACHE=0 INDICES_SPEEDHACK=0 DRAW_SPEEDHACK=2 SINGLE_THREADED_GC=1 install 
cd /vita-dev/soulcalibur_vita/build
cmake ..
make -j64 clean
make -j64 send
#make